name: Get YouTube Transcripts

on:
  workflow_dispatch:

jobs:
  get-transcripts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Show initial directory
      run: |
        pwd
        ls -la
        
    - name: Run transcript script
      run: python your_script.py
        
    - name: Show files after script
      run: |
        echo "Current directory:"
        ls -la
        echo "\nChecking transcripts directory:"
        ls -la transcripts || echo "No transcripts directory"
        
    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Add transcripts" || echo "No changes to commit"
        git push
