name: Get YouTube Transcripts

on:
  schedule:
    - cron: '0 0 * * 6'  # Runs at 00:00 on Saturday
  workflow_dispatch:  # Allows manual triggering

jobs:
  get-transcripts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create transcripts directory
      run: mkdir -p transcripts
        
    - name: Run transcript script
      run: python your_script.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add transcripts/
        git commit -m "Add transcripts $(date +'%Y-%m-%d')" || exit 0
        git push
